### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by iag3** [steventroughtonsmith/windowmanager-playgroundbook#1]
First of all: Thanks for the great project!

I tried to reuse the code just for fun but for some reason I do not get the same performance you have. The code is the same!

Could you maybe share your `book.yaml` file with your configuration? 

Mine looks like this:

```yaml
resources: assets # Optional
cover: cover.jpg # Optional
deployment_target: ios10.0 # Optional
imports: # Optional, defaults to UIKit
 - UIKit
 # - CoreGraphics
 - MapKit
 - PlaygroundSupport
 - Foundation
chapters:
  - name: Chapter
    edge_to_edge_live_view: false # defaults to true
    live_view_mode: "VisibleByDefault" # defaults to "HiddenByDefault"
```

**_Do you have any idea what might be wrong?_**

_Thanks in advance_
